variable "prefix" {}
variable "env" {}
variable "region" {}
variable "codecommit_repo_http_url" {}
variable "codecommit_repo_arn" {}
variable "s3_cache_bucket" {}
variable "s3_cache_bucket_arn" {}
variable "s3_artifact_bucket" {}
variable "s3_artifact_bucket_arn" {}
variable "s3_log_bucket" {}
variable "s3_log_bucket_arn" {}
variable "cloudwatch_codebuild_log_group_name" {}
variable "ecr_registry_name" {}
variable "aws_account_id" {}
variable "docker_app_image_name" {}
