variable "prefix" {}
variable "env" {}
variable "region" {}
variable "s3_cache_bucket" {}
variable "s3_cache_bucket_arn" {}
variable "s3_artifact_bucket" {}
variable "s3_artifact_bucket_arn" {}
variable "s3_log_bucket" {}
variable "s3_log_bucket_arn" {}
variable "cloudwatch_codebuild_log_group_name" {}
variable "codecommit_repo_name" {}
variable "codecommit_repo_arn" {}
variable "codebuild_build_and_test_project_arn" {}
variable "codebuild_build_and_test_project_name" {}
variable "codebuild_build_docker_image_project_arn" {}
variable "codebuild_build_docker_image_project_name" {}
